/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9storybook;

/**
 *
 * @author hsomotsiu
 */
public class EndFrame extends javax.swing.JFrame {
    private StorybookModel myModel;

    /**
     * Creates new form EndFrame
     * @param model
     */
    public EndFrame(StorybookModel model) {
        initComponents();
        this.myModel = model;
        welcomeLabel.setText("Welcome, "+myModel.getUserName()+".");
        
    }

    EndFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private static class welcomeLabel {

        private static void setText(String string) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public welcomeLabel() {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        instructionLabel = new javax.swing.JLabel();
        leftDoorButton = new javax.swing.JButton();
        rightDoorButton = new javax.swing.JButton();
        leftdoorButton = new javax.swing.JButton();
        rightdoorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("Welcome, Celine.");

        jLabel1.setText("You have been accused of Witchcraft!");

        instructionLabel.setText("Pick a door to determine yout verdict.");

        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/Door.GIF"))); // NOI18N
        leftDoorButton.setToolTipText("");
        leftDoorButton.setBorderPainted(false);
        leftDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDoorButtonActionPerformed(evt);
            }
        });

        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/Door.GIF"))); // NOI18N
        rightDoorButton.setBorderPainted(false);

        leftdoorButton.setText("Exit Tribunal");
        leftdoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftdoorButtonActionPerformed(evt);
            }
        });

        rightdoorButton.setText("Next Trial -->");
        rightdoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightdoorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leftdoorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(rightdoorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leftDoorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rightDoorButton)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftDoorButton)
                    .addComponent(rightDoorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftdoorButton)
                    .addComponent(rightdoorButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDoorButtonActionPerformed
        // TODO add your handling code here:
        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/Door.GIF")));
        instructionLabel.setText("You are Guilty! Prepare to eaten");
        leftDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/tiger.GIF")));
    }//GEN-LAST:event_leftDoorButtonActionPerformed

    private void rightdoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightdoorButtonActionPerformed
        // TODO add your handling code here:
        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/Door.GIF")));
        instructionLabel.setText("You are Innocent! Sorry about that. Please accept this lady");
        rightDoorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab9storybook/lady.GIF")));
        StartFrame myStartFrame = new StartFrame(myModel);
        myStartFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rightdoorButtonActionPerformed

    private void leftdoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftdoorButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_leftdoorButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton leftDoorButton;
    private javax.swing.JButton leftdoorButton;
    private javax.swing.JButton rightDoorButton;
    private javax.swing.JButton rightdoorButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
